### ISSUE TITLE
dcs.sh under dcs/ folder is missing

### ISSUE THREAD

**Issue by prajnaupadhyay** [carrot2/carrot2#121]
The README states that the DCS server can be started by running `./dcs` from inside dcs/ folder but it is missing. Please update the README with the latest instructions so that the service can be used.

**Comment by dweiss** [comment]
When I download the latest release from:
https://github.com/carrot2/carrot2/releases/tag/release%2F4.2.1

it comes with the scripts intact under the dcs folder. Please be more specific about which version you've downloaded.

**Comment by dweiss** [comment]
Perhaps there is some misunderstanding in that the distribution zip contains the top-level folder with the distribution name. You need to enter into that folder and then you'll find the dcs inside.

**Comment by prajnaupadhyay** [comment]
Thanks a lot! I can start the server now. 

Instead of the stable release version, I was working with the latest clone of this repository (d31c5f6), which I think is continuously being updated.
