### ISSUE TITLE
Switch to Yarn 2 and PnP linker for building frontend

### ISSUE THREAD

**Issue by stanislawosinski** [carrot2/carrot2#139]

**Comment by dweiss** [comment]
I'd like to release 4.4.0 and this can be a larger change to build files and dependencies. Can we do it for the next release?

**Comment by stanislawosinski** [comment]
It shouldn't be that bad. Yarn 2 is still bootstrapped from Yarn 1, so the Gradle side of things should remain the same (we did that with l4g some time ago). Yarn 3 promises some better tools for fixing security alerts and I wanted to test that. Plus, node_modules will be gone in the webapp build.

**Comment by dweiss** [comment]
ok, I'll wait.
