### ISSUE TITLE
FireFox (maybe others) - searching from the address bar or context menu adds + between words, limiting results

### ISSUE THREAD

**Issue by Andy2No** [carrot2/carrot2#1490]
With carrot2.org set as the default search engine (for example) in Firefox, searching from the address bar adds a plus between each word passed to it, unlike other search engines.  The same happens using the context menu by selecting some text then right clicking to use "Search carrot2.org for ...".

This typically limits the number of search results, unless the + symbols are manually edited out and replaced with spaces.  As a genuine example, which reminded me to post this, I searched for

reface decksaver

from the address bar, having set carrot2.org as the default search engine.

The carrot2.org search box was then filled with 

reface+decksaver

which gave only one result.  Changing the + to a space gave 40 results.

While this isn't hard for someone to do, it's the sort of usability feature which can put people off using something, and might just make some people conclude that carrot2 tends to give very few results.

**Comment by dweiss** [comment]
Thanks. I'll take a look. Looks like something is wrong with parsing URL-encoded characters.

**Comment by dweiss** [comment]
Can I ask you how (or where) did you get and install the firefox search extension for Carrot2?We used to have one but I don't think we've been maintaining it. 

Technically, Carrot2 is not a general purpose search engine - it's a demo of the project and will only let you send a limited number of queries before it quota-blocks the source IP address.

**Comment by Andy2No** [comment]
I didn't realise it was limited.

I enabled the Add button for search engines via URL, using the method described here:

https://www.reddit.com/r/firefox/comments/1dhcp8v/add_my_own_url_as_default_search_engine/

"
 i) Enable the 'Add' Search Engine plugins button on the Settings > Search page ('about:preferences#search').

Open the Advanced Preferences editor ('about:config') and create a new (hidden) boolean preference by pasting in 'browser.urlbar.update2.engineAliasRefresh'... click the '+' symbol... and check new preference is set to 'true'. (May need a browser restart to see the 'Add' button appear below the normal 'Search Shortcuts' box.)

Although enabling the 'Add' button is simple... it is less flexible... i.e. can't add favicons for new search plugins. 
"

I then used the "Change search settings" gear icon, at the end of the list of installed search engines that appears at the bottom of the pop-up box when I click the address bar.  The gear icon is bottom right of that box.  When I click that, there is now an "Add" button under the list of installed search engines, near bottom right.  Using that, I pasted in a url from searching carrot2.org, replacing the search terms part with %s.  E.g. using carrot2.org to search for carrot2:

https://search.carrot2.org/#/search/web/carrot2/folders

I can change that to

https://search.carrot2.org/#/search/web/%s/folders

Further up that page, under Default Search Engine, I can now choose carrot2 from the list.

**Comment by dweiss** [comment]
Ok, I know what the problem is - we decode the query using the spec's URI decoding rules (percent decoding) while white spaces are encoded as '+' by firefox (old-style URL encoding). I'll look into correcting this.

This said, I have to warn you again that you'll hit the limits described in [1] sooner or later.

[1] ![image](https://github.com/user-attachments/assets/990e1ff6-aebb-4f69-a353-e18fa0604bb2)

**Comment by dweiss** [comment]
The underlying url decoding is in React's router. We have little control over it. FF should encode those white spaces using %20 when they're part of the URL (not the query string) but it doesn't - it's been mentioned all over the web, for example here [1].

https://support.mozilla.org/mk/questions/1396405

**Comment by dweiss** [comment]
We can probably add a workaround as per this hint:

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/decodeURIComponent#decoding_query_parameters_from_a_url

**Comment by dweiss** [comment]
I've implemented the workaround and checked that it works locally. I'll deploy this version next week to the public service demo, thank you for reporting the problem.

**Comment by dweiss** [comment]
Seems to work fine - https://search.carrot2.org/#/search/web/data+mining/folders

**Comment by Andy2No** [comment]
It does!  Thanks.
