### ISSUE TITLE
How to build in Windows environment?

### ISSUE THREAD

**Issue by kimjw0820** [carrot2/carrot2#157]
hello :) 

How to build in Windows environment?

OS : windows 10
I tried to build by installing jsdk 1.7 and 1.8.
I couldn't find any build guide documentation.

command:
.\gradlew.bat clean build

An error occurs at 97%

\carrot2\dcs\tests\build\test-outputs\test
OUTPUT-org.carrot2.dcs.it.DcsExamplesTest.txt
OUTPUT-org.carrot2.dcs.it.DcsGzipTest.txt
OUTPUT-org.carrot2.dcs.it.DcsServiceScriptTest.txt
OUTPUT-org.carrot2.dcs.it.DcsServiceTest.txt

ex) OUTPUT-org.carrot2.dcs.it.DcsExamplesTest.txt

  1> 11:17:41 INFO console: Using distribution from: xxx\carrot2\dcs\distribution\build\dist mirrored to: xxx\carrot2\dcs\tests\build\test-tmp\tests-20220807111735-516\0000 has -space
  1> [C:\WINDOWS\system32\cmd.exe, /S, /C, ", xxx\carrot2\dcs\tests\build\test-tmp\tests-20220807111735-516\0000 has-space\dcs, - -shutdown-token, _shutdown_, --port, 0, --gzip, true"]
  1> 11:17:41 INFO console: Launching DCS at: xxx\carrot2\dcs\tests\build\test-tmp\tests-20220807111735-516\0000 has-space
   > java.nio.charset.MalformedInputException: Input length = 1
   > at java.base/java.lang.String.throwMalformed(String.java:1240)
   > at java.base/java.lang.String.decodeUTF8_UTF16(String.java:1191)
   > at java.base/java.lang.String.newStringUTF8NoRepl(String.java:728)
   > at java.base/java.lang.String.newStringNoRepl1(String.java:756)
   > at java.base/java.lang.String.newStringNoRepl(String.java:738)
   > at java.base/java.lang.System$2.newStringNoRepl(System.java:2390)
   > at java.base/java.nio.file.Files.readString(Files.java:3369)
   > at org.carrot2.dcs.it.ForkedDcs.<init>(ForkedDcs.java:86)
   > at org.carrot2.dcs.it.DcsServiceRule.before(DcsServiceRule.java:31)
   > at com.carrotsearch.randomizedtesting.rules.TestRuleAdapter$1.before(TestRuleAdapter.java:26)
   > at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:35)
   > at org.junit.rules.RunRules.evaluate(RunRules.java:20)
   > at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
   > at org.junit.rules.RunRules.evaluate(RunRules.java:20)
   > at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
   > at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
   > at com.carrotsearch.randomizedtesting.rules.SystemPropertiesInvariantRule$1.evaluate(SystemPropertiesInvariantRule.java:59)
   > at org.junit.rules.RunRules.evaluate(RunRules.java:20)
   > at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
   > at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:390)
   > at com.carrotsearch.randomizedtesting.ThreadLeakControl.lambda$forkTimeoutingTask$0(ThreadLeakControl.java:850)
   > at java.base/java.lang.Thread.run(Thread.java:833)
   > com.carrotsearch.randomizedtesting.ResourceDisposalError: Resource in scope SUITE failed to close. Resource was registered from thread Thread[id=19, name=SUITE-DcsExamplesTest-seed#[A09975B88D992910]-worker, state=RUNNABLE, group=TGRP-DcsExamplesTest], registration stack trace below.
   > at java.base@17.0.4/java.lang.Thread.getStackTrace(Thread.java:1610)
   > at app//com.carrotsearch.randomizedtesting.RandomizedContext.closeAtEnd(RandomizedContext.java:157)
   > at app//com.carrotsearch.randomizedtesting.RandomizedTest.newTempDir(RandomizedTest.java:425)
   > at app//org.carrot2.dcs.it.ForkedDcs.<init>(ForkedDcs.java:67)
   > at app//org.carrot2.dcs.it.DcsServiceRule.before(DcsServiceRule.java:31)
   > at app//com.carrotsearch.randomizedtesting.rules.TestRuleAdapter$1.before(TestRuleAdapter.java:26)
   > at app//com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:35)
   > at app//org.junit.rules.RunRules.evaluate(RunRules.java:20)
   > at app//com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
   > at app//org.junit.rules.RunRules.evaluate(RunRules.java:20)
   > at app//com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
   > at app//com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
   > at app//com.carrotsearch.randomizedtesting.rules.SystemPropertiesInvariantRule$1.evaluate(SystemPropertiesInvariantRule.java:59)
   > at app//org.junit.rules.RunRules.evaluate(RunRules.java:20)
   > at app//com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
   > at app//com.carr

**Comment by dweiss** [comment]
JDK11 is the minimum required platform, please try that first. We test on Windows and everything seems to be passing:
https://github.com/carrot2/carrot2/runs/7709910315?check_suite_focus=true
