### ISSUE TITLE
Increasing heap size in dcs

### ISSUE THREAD

**Issue by foboni** [carrot2/carrot2#162]
I'm getting `java.lang.OutOfMemoryError: Java heap space` when I try to cluster a few thousands of documents (tried max: 2000).

While searching similar issues, I found this answer https://stackoverflow.com/a/60623765
But it uses `carrot2-workbench`

Env Resources:
```
.4 CPU
800M MEM (Also tried with 1G but failed)
```

Is there anyway to modify the heap space by passing arguments or config file while starting `dcs` ?

**Comment by dweiss** [comment]
Yes, you can set DCS_OPTS environment variable and bump the heap via jvm settings. 
```
https://github.com/carrot2/carrot2/blob/master/dcs/distribution/src/main/assembly/dcs#L11-L14
```

I'll leave this open so that I can write better documentation for this.

**Comment by foboni** [comment]
Thanks @dweiss 

Setting this in environment increased the heap size

`DCS_OPTS=-Xmx512m`
