### ISSUE TITLE
Number of results from web-search small

### ISSUE THREAD

**Issue by some-avail** [carrot2/carrot2#163]
A great project i like very much, but the number of results from a web-search are quite small. Can this number be set somewhere? (i have seen the var maxresults but havent analyzed the code).

Or is it some deal with etools to limit the number. But an open source project should be open on this matter, or not?. Also it would be nice if one could use the results from major search-engines directly, to decrease dependence on the Etools metasearch-engine (who also use other engines).

Maybe the bulk of the code is donated by Etools, which is probably a company with interests. 

Thanx, Joris.

**Comment by dweiss** [comment]
Carrot2 is about clustering. We have a friendly agreement with ETools to provide search results feed but it's just that - a friendly agreement. We used to have major search engines but they removed search API feeds progressively (terms and conditions, terms and conditions...). It's not our fault, sorry.
