### ISSUE TITLE
New functionality to process a list of links for clustering

### ISSUE THREAD

**Issue by some-avail** [carrot2/carrot2#164]
Would it be possible to create a function to mine web-links?

One would have to enter a web-address on which page there exists a list of links. These links can be "mined" and fed to the clustering-engine, possibly recursively to a certain depth. 

This might create a lot flexibily and usefullness.

**Comment by dweiss** [comment]
We focus on clustering only. Such tools can be built externally an utilize c2 - no problem there. You can even use existing tools like https://nutch.apache.org/ or https://github.com/internetarchive/heritrix3.

**Comment by some-avail** [comment]
Your reasoning would be understandable if you didnt have a front-end but only a back-end. But you do have a front-end, or is only meant for testing-purposes of the backend?

**Comment by dweiss** [comment]
It's a showcase/ demo of the technology, that's it.
