### ISSUE TITLE
CSV import fails

### ISSUE THREAD

**Issue by tdunning** [carrot2/carrot2#183]
On version 4.5.0
![image](https://user-images.githubusercontent.com/250490/236645115-29cfa470-e571-45cf-a9f8-74b170be944a.png)

I get an error "Unknown file type text/csv" when I try to bring in a CSV file

![image](https://user-images.githubusercontent.com/250490/236645067-21e09346-bc0c-4ea3-abf1-d567726fe44a.png)

Happy to pull any additional diagnostics if it would help.  I don't see instantly how to change logging config (I see the command line option, but no sample log4j config to tweak).

Will try to replicate on earlier versions.

**Comment by tdunning** [comment]
Fails on 
```
version: 4.4.3
build date: 2022-08-22T16:00+02:00
git rev: 28c40be8a2dc53e5fcdb61a40de5b0cf548ff8d1
```
as well

**Comment by tdunning** [comment]
Also fails on
```
version: 4.3.1
build date: 2021-07-06T08:00+02:00
git rev: 5ee1bc852738bce97fe8be355720f5809fb4cdec
```

**Comment by dweiss** [comment]
Hi Ted! I can reproduce - looks like a bug somewhere. I'll take a look.

**Comment by tdunning** [comment]
Same on 
```
version: 4.2.1
build date: 2021-03-29T11:00+02:00
git rev: 936bcf7fa48e03fafffdf4e6f15b36074d161e6e
```

**Comment by tdunning** [comment]
So it doesn't look like a recent change that did this.

**Comment by dweiss** [comment]
Nope, seems like CSV isn't on the mime type list in file-parser.js.

**Comment by dweiss** [comment]
I've added the csv mime type and pointed it at the excel parser, works for me locally.
![image](https://user-images.githubusercontent.com/199470/236645956-089e6351-3a2e-476e-ae59-f1b1d9e69783.png)

This must be an oversight that's been out there since the very beginning. Thank you for reporting this!

**Comment by tdunning** [comment]
Wow.  Quick.

Excellent news.

**Comment by dweiss** [comment]
We've neglected this a bit but I'll do some library upgrades and will release a point release next week. Please rebuild from sources on the master branch if you need it now.

**Comment by tdunning** [comment]
Can you point to compilation directions?

I don't see them in the docs.

I just tried `./gradlew` as a shot in the dark. Failed. Probably because I
don't know about gradle much at all.

**Comment by dweiss** [comment]
Actually, you can get the most recent build from gh: https://github.com/carrot2/carrot2/actions/runs/4903554913

**Comment by dweiss** [comment]
FYI:
./gradlew -p distribution assemble
then the artifacts are under distribution/build/distZip/

Easier to get them from a github build above though.

**Comment by tdunning** [comment]
The fix works great.

**Comment by dweiss** [comment]
Hi Ted. I pushed 4.5.1 release yesterday, available here:
https://github.com/carrot2/carrot2/releases/tag/release%2F4.5.1
