### ISSUE TITLE
Carrot2 Web Application - documentation request

### ISSUE THREAD

**Issue by batomz** [carrot2/carrot2#190]
The Carrot2 web app and interface are amazing!  I have it working with a static xml document but cannot find an example of using it dynamically. Specifically looking for how to configure XmlDocumentSource.xml in source-xml-attributes.xml to use a dynamic URL (parameterized URL) via org.carrot2.util.resource.URLResourceWithParams.
source-xml-attributes.xml  example: 
``
      <attribute key="XmlDocumentSource.xml">
        <value>
          <wrapper class="org.carrot2.util.resource.URLResourceWithParams" url="http://localhost:8080/${srcxmlfile}"/>
        </value>
      </attribute>
``
Then calling with http://localhost:8080/c2/search?source=xml&query=test1&srcxmlfile=mycontent.xml does not seem to work. Would it be possible to add a snippet to the docs to show how to alter the xml source url with a parameter in the documentation: https://get.carrot2.org/head/manual/index.html

**Comment by dweiss** [comment]
Thanks! I think you're referring to previous version (3.x) of Carrot2 - that's quite an old version to use. The latest version departs from the "document source" model in favor of a plain HTTP/REST clustering service. Document sources are left for the user to implement in any way they desire (the current demo frontend implements a few example sources in javascript, https://search.carrot2.org/#/workbench).

This said, what you're trying to achieve has been mentioned here:
https://issues.carrot2.org/browse/CARROT-1101

We then decided that it wouldn't be safe to allow overriding these URL parameters - the corresponding attribute of XmlDocumentSource is marked as Internal; the webapp specifically ignores these attributes and will only allow their configuration from within the configuration blocks in source-xml-attributes.xml (so, a constant, effectively).

https://github.com/carrot2/carrot2/blob/release/3.16.3/applications/carrot2-webapp/src/org/carrot2/webapp/QueryProcessorServlet.java#L419-L421

Even if you removed that restriction, you'd need to pass the XmlDocumentSource.xmlParameters as a Map for the binder (map keys are not automatically converted).

I would encourage you to take a look at the latest release: the frontend there is more modern and you can tweak the js code to fetch any data you like, then feed it to the http rest service in a standard format.
