### ISSUE TITLE
Upgrade node to 18.18.2 and yarn to 1.22.19

### ISSUE THREAD

**Issue by chenrui333** [carrot2/carrot2#202]
Looks like the project is using node 16, which is EOL already.

https://github.com/carrot2/carrot2/blob/fd5bf2b56de688ddc4daa23639b7e13e781f5799/versions.toml#L3

![image](https://github.com/carrot2/carrot2/assets/1580956/8f803035-e173-4aa0-b550-ff81e1d8368e)

**Comment by dweiss** [comment]
Right. And upgrading the entire build stack (gatsby, etc.) is not a trivial thing. We'll get there, eventually.

**Comment by dweiss** [comment]
I've upgraded node to 18.18.2 and yarn to 1.22.19. Pushing it further makes me worry that things will break - I'll leave it for the future.

**Comment by dweiss** [comment]
Sadly, upgrading node and yarn broke interactive development somehow (yarn start no longer works properly).

**Comment by dweiss** [comment]
That's fine, I'm looking at it.

**Comment by dweiss** [comment]
It seems unrelated - everything works in 2ebc59b01b1ada55a but something broke dev mode even before the upgrade. I'll file a separate issue.
