### ISSUE TITLE
request a new release

### ISSUE THREAD

**Issue by chenrui333** [carrot2/carrot2#207]
I think there is some encoding issue for the codebase, which caused some [downstream patching issue](https://github.com/Homebrew/homebrew-core/pull/153438), can you create a release for [this commit](https://github.com/carrot2/carrot2/commit/b8ad381aa8d9fc7ed7308e8658bae6ce764ddb4a)?

![image](https://github.com/carrot2/carrot2/assets/1580956/5a01b78e-1847-478e-aa63-95e5c58e61f8)

**Comment by dweiss** [comment]
I will release when I'm done with downstream projects. The patch should apply just fine - use binary mode or convert the patch to unix line endings.

**Comment by chenrui333** [comment]
I will try fixing the encoding issue, but would you mind merging #208 for the long run?

**Comment by dweiss** [comment]
Done. Hope it'll help with, ahem, brewing the new compilation formula.
https://github.com/carrot2/carrot2/releases/tag/release%2F4.5.3

I don't know anything about homebrew but looking at the source of that compilation formula, I'd say it may be problematic - switching gradle version (the build tool) is quite risky as different versions tend to behave in slightly different ways. You also can't easily reuse system node and yarn - the plugin used for compilation of js sources will download and install them locally anyway (and when you switch versions, weird things can happen).
