### ISSUE TITLE
Error When Searching

### ISSUE THREAD

**Issue by sirinath** [carrot2/carrot2#24]
I get the following error when searching:

![image](https://user-images.githubusercontent.com/637415/88176073-61ddf500-cc44-11ea-8276-2c6b0514519b.png)

**Comment by dweiss** [comment]
Works for me. Can you look at the debug console/ networking and see what etools returns? Perhaps you ran into the per-IP limit?

**Comment by sirinath** [comment]
I just went to: https://search.carrot2.org/#/web and typed Java out of curiosity. I have tried this only once, so it might not be possible to hit IP limits.

I am on Opera GX Browser on Win 10 64x.

I cannot find debug console/ networking and etools.

**Comment by dweiss** [comment]
Does this work? https://www.etools.ch/

**Comment by sirinath** [comment]
Yes.

**Comment by dweiss** [comment]
Can you try with a different browser? I don't have opera but I feel like this may be the cause.

**Comment by sirinath** [comment]
Works on Chrome.

**Comment by dweiss** [comment]
Thanks - we'll investigate, it's a bug then.

**Comment by sirinath** [comment]
Yes. Possibly because Opera has Ad Blocker and Tracking Blocker which comes with the browser. In Chrome I don't have an Ad Blocker.

**Comment by dweiss** [comment]
It's not an ad blocker, I think. I believe it's the VPN that Opera is using that causes your addresses to be blocked by our search results provider.

**Comment by sirinath** [comment]
I am not using the VPN

**Comment by dweiss** [comment]
I really don't know. I installed Opera and everything works - with the VPN, etc.
![capture-6](https://user-images.githubusercontent.com/199470/88264470-18d18380-cccc-11ea-87ae-71f3596c14b0.png)

**Comment by dweiss** [comment]
You could try to debug why the network request to ETools returns an error - the error code and HTTP message body would be informative. Here's how to enable development tools in Opera:
https://superuser.com/questions/1010743/how-to-open-devtools-in-opera

I really can't help out more without being able to reproduce the problem.

**Comment by sirinath** [comment]
I have `[Deprecation] HTML Imports is deprecated and will be removed in M80, around February 2020. Please use ES modules instead. See https://www.chromestatus.com/features/5144752345317376 and https://developers.google.com/web/updates/2019/07/web-components-time-to-upgrade for more details.`

**Comment by dweiss** [comment]
Look at the network tab and click xhr, then locate the parter search request. See this:

**Comment by dweiss** [comment]
![image](https://user-images.githubusercontent.com/199470/88270880-9dc19a80-ccd6-11ea-8f62-d21158cb4513.png)

**Comment by sirinath** [comment]
![image](https://user-images.githubusercontent.com/637415/88273295-965eb900-ccf7-11ea-9001-1ed32a8930fb.png)

**Comment by dweiss** [comment]
You have the reason at the bottom of the screenshot - (blocked by adblocker).

**Comment by sirinath** [comment]
![image](https://user-images.githubusercontent.com/637415/88273414-c8701b00-ccf7-11ea-9dec-f4c1304fb08d.png)

**Comment by dweiss** [comment]
Either opera or your system has an ad-blocker.

**Comment by dweiss** [comment]
I don't know why this URL qualifies as an ad - it isn't.

**Comment by sirinath** [comment]
Yes.

As I mentioned before this happens when the AdBlocker is enabled:

> Yes. Possibly because Opera has Ad Blocker and Tracking Blocker which comes with the browser. In Chrome I don't have an Ad Blocker.
