### ISSUE TITLE
Clustering Engine Error

### ISSUE THREAD

**Issue by GreySkySpin** [carrot2/carrot2#29]
Getting a Clustering Engine Error on Android Chrome.

![Screenshot_20200929-171722~2](https://user-images.githubusercontent.com/42599782/94571481-b6bb6e80-0278-11eb-9827-a77f9b2ae851.png)

This is from Carrot2:
version: 4.0.0
build date: 2020-07-14T11:00+02:00
git rev: 6a5e2ff984b3ec60375fd475c7cdcd25f7403beb

**Comment by stanislawosinski** [comment]
Thanks for the report, this was an expired certificate on our server. Should be fine now.
