### ISSUE TITLE
4.0.2 release does not have carrot2-4.0.2.zip

### ISSUE THREAD

**Issue by chenrui333** [carrot2/carrot2#30]
👋  it looks like the latest release does not have the release artifact `carrot2-4.0.2.zip`, just feel like I should call it out. :)

**Comment by dweiss** [comment]
Thank you! I had to make a few more minor releases because of how POMs are structured... it's a long story. I will upload artifacts shortly.

**Comment by chenrui333** [comment]
Thanks!!
