### ISSUE TITLE
Add 'enable' boolean options to filters in Lingo

### ISSUE THREAD

**Issue by dweiss** [carrot2/carrot2#43]
GH copy of https://issues.carrot2.org/browse/CARROT-1278

**Comment by stanislawosinski** [comment]
This is already done on the workbench-webapp branch, I can merge to master it if needed.

**Comment by dweiss** [comment]
Resolve the issue when merging that branch? This changes the API - should be mentioned in release notes (docs) and perhaps documentation if it's affected anywhere.

**Comment by dweiss** [comment]
I'll modify the code slightly and fill in the remaining details.
