### ISSUE TITLE
Polish documentation

### ISSUE THREAD

**Issue by stanislawosinski** [carrot2/carrot2#49]
- [x] Make it clear how matching is done. Are the rules the same as for the static files and per-request dictionaries?
- [x] Describe the consequences of filtering out words (removed from processing, but will still appear in labels).
- [x] Make the information "how do I add stopwords?" easier to find (or add a FAQ).
- [x] Replace "attributes" with "parameters" in reference pages, the REST and Java API documentation use "parameters".
- [x] Mention REST per-request dictionaries in the Dictionaries section.
- [x] Add REST API subsection for parameter customization (link to the reference, JSON parameters Workbench export).
- [x] Describe a basic procedure for tuning dictionaries (use Workbench, copy to the static or per-request dictionary).
- [x] Group release notes like in the L4G documentation (New features, Improvements, Bugs, API changes).
- [x] Don't use relative links to local Workbench and search-app instances, they won't work for the documentation viewed directly from GitHub hosting.

**Comment by dweiss** [comment]
> Are the rules the same as for the static files and per-request dictionaries?

Yes. I wonder if we should keep the plain-text dictionaries or just replace them in favor of those JSON files. Fewer things to explain.
