### ISSUE TITLE
Incorrect image URL prefix when documentation is built using Gradle

### ISSUE THREAD

**Issue by stanislawosinski** [carrot2/carrot2#71]
When I assemble the DCS using gradle, the top-level index.html is generated with an incorrect (`../`) prefix for images, which causes 404 errors. When I build the documentation by directly calling `yarn run build`, then the prefix in the top-level index.html is correct (`./`). Puzzling.

**Comment by stanislawosinski** [comment]
Maybe that's related to the working directory when building? That would be insane though.

**Comment by dweiss** [comment]
If you see it on you local build then clean everything first. I've see gatsby caches interact very weirdly when doing manual runs (develop) followed by production builds. I assume that if you run it from a clean state and it's building ok - it's working fine. I don't want to look into what happens in that js code, it's too weird for me.

**Comment by stanislawosinski** [comment]
It's on Bamboo. It appears that `./gradle clean` executed in the build does not delete `doc/.cache` and `doc/public` -- is that indented? When running the build with a clean checkout the URLs get built correctly.

**Comment by dweiss** [comment]
> it appears that ./gradle clean executed in the build does not delete doc/.cache and doc/public

I just checked and it should remove those folders on clean... See here:
https://github.com/carrot2/carrot2/blob/master/gradle/node/yarn-project.gradle#L130-L137

Which bamboo build is it, again? Very odd...

**Comment by dweiss** [comment]
I think I see where the problem is.

**Comment by dweiss** [comment]
Should be ok now.
