### ISSUE TITLE
Extract common UI code to a separate project

### ISSUE THREAD

**Issue by stanislawosinski** [carrot2/carrot2#75]

**Comment by dweiss** [comment]
Everything seems to work. The only problem may be that submodules are added with git (ssh) URLs. Somebody who clones the repo via http (without a local github-access ssh key) will not be able to clone submodules. This is what happened to this travis build:

https://travis-ci.org/github/carrot2/carrot2/jobs/756231752

Perhaps the URL in submodules should be switched to https.
