### ISSUE TITLE
How can I fetch "content" of document when I use REST API?

### ISSUE THREAD

**Issue by rider8581** [carrot2/carrot2#77]
I have installed carrot2 and trying to use REST API for document clustering.

![image](https://user-images.githubusercontent.com/52605718/105009849-fdd89580-5a08-11eb-91d1-3535b57db951.png)
In its API, it seems it just accepts the title of the document.
I am not sure if I can fetch not only the title but also the content of the document.
Please guide me if it is possible and if possible, how to do it.
Thank you.

**Comment by dweiss** [comment]
In the new API, field titles are for your convenience only, actually. All fields are clustered, regardless of the name.  See the description of "documents" request section here:
https://carrot2.github.io/release/4.1.0/doc/rest-api-basics/#clustering

**Comment by rider8581** [comment]
If my documents covers not only English but also some other languages like Spanish, Chinese, etc, how should I set the "language" parameter?

**Comment by dweiss** [comment]
You can't cluster in multiple languages as part of one request. You should split your documents into their respective language on the client side and then issue multiple requests, adjusting the "language" parameter of each request. See the /list REST endpoint documentation on how to retrieve the list of supported languages (for a given algorithm).
