### ISSUE TITLE
loading CSV and Excel does not work

### ISSUE THREAD

**Issue by vpodpecan** [carrot2/carrot2#95]
When loading CSV or Excel files I always get the "Unknown file type" error and no fields are shown. Even the enclosed sample files (csv, xslx) cannot be loaded. JSON work fine, though. Version affected: 4.1.0

**Comment by dweiss** [comment]
What browser is this? Is there anything on the js console?

**Comment by vpodpecan** [comment]
Latest FF 86.0.1, nothing reported in the console. I believe this is an internal issue. When loading a file instead of displaying the detected fields I get:
```
No natural text content detected
Unknown file type text/csv.
```
for `serverfault.csv` and `serverfault.xslx` samples. `serverfault.json` loads fine and displays available fields.

**Comment by dweiss** [comment]
![image](https://user-images.githubusercontent.com/199470/112157966-02c3ec00-8be8-11eb-868c-9b5bf8782a0f.png)

Really not sure... can't reproduce what you're seeing.

**Comment by vpodpecan** [comment]
Now that is interesting. It must be my local issue because even on [https://search.carrot2.org](https://search.carrot2.org) I cannot load csv and xlsx. I've tried FF, Opera and some older Chrome and it's the same. Let's close this issue for now.

**Comment by dweiss** [comment]
I really have no idea. Can it be that your browser is somehow set up with restricted security policy? Let me know if you find out what the problem is!
